# Generated by Django 4.2.14 on 2024-10-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('custom', 'Custom Services'), ('cloud', 'Cloud Services'), ('standard', 'Standard Services')], default='standard', max_length=10),
        ),
    ]
