# Generated by Django 4.2.19 on 2025-03-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_technology_techstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tech_stacks',
            field=models.ManyToManyField(blank=True, to='coreapp.techstack'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies_used',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.ManyToManyField(blank=True, max_length=200, to='coreapp.techstack'),
        ),
    ]
